#!/usr/bin/ansible-playbook
---
- name: Configure machine
  hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: Include vars.yml file
      include_vars: vars.yml

    - name: Run ubuntu.yml playbook
      include_tasks: ubuntu/main.yml
      when: ansible_facts["distribution"] == "Ubuntu"
