#!/usr/bin/ansible-playbook
---
- name: Configure machine
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  tasks:
    - name: Include vars.yml file
      include_vars: vars.yml

    - name: Run Linux playbooks
      include_tasks: os/linux/main.yml

    - name: Run Ubuntu specific playbooks
      include_tasks: os/ubuntu/main.yml
      when: ansible_facts["distribution"] == "Ubuntu"
