---
- name: Configure ubuntu machine
  hosts: my_ubuntu
  become: yes
  gather_facts: no
  roles:
    - ubuntu/system
    - ubuntu/apps
    - ubuntu/apps/jfrog-cli
    - ubuntu/apps/containerd
    - name: ubuntu/apps/kubernetes
      vars:
